# Generated by Django 3.2.6 on 2022-05-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0002_studentprofile_fromfilld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='StudentDob',
            field=models.DateField(null=True),
        ),
    ]
