# Generated by Django 3.2.6 on 2022-05-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0003_alter_studentprofile_studentdob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='AddmissionY',
            field=models.DateField(null=True),
        ),
    ]
