# Generated by Django 3.2.6 on 2022-05-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0004_alter_studentprofile_addmissiony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='JobCrit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='Semester',
            field=models.IntegerField(default=0),
        ),
    ]
