# Generated by Django 3.2.6 on 2022-05-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0005_auto_20220530_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='FosemMS',
            field=models.FileField(default='', upload_to='WEBAPP/files'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='FsemMS',
            field=models.FileField(default='', upload_to='WEBAPP/files'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='SsemMS',
            field=models.FileField(default='', upload_to='WEBAPP/files'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='Stdimage',
            field=models.ImageField(default='', upload_to='WEBAPP/images'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='TsemMS',
            field=models.FileField(default='', upload_to='WEBAPP/files'),
        ),
    ]
