# Generated by Django 3.2.6 on 2022-05-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0009_auto_20220531_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='activeJobs',
            field=models.TextField(null=True),
        ),
    ]
