# Generated by Django 3.2.6 on 2022-05-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0011_company_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrainTitle', models.CharField(default='', max_length=50)),
                ('TrainDesc', models.CharField(default='', max_length=250)),
                ('TrainCrit', models.IntegerField(default=0)),
                ('TrainMarks', models.IntegerField(default=0)),
                ('TrainDept', models.CharField(default='', max_length=50)),
                ('Company', models.CharField(default='', max_length=50)),
                ('TrainAppl', models.IntegerField(default=0)),
                ('ApplList', models.TextField(null=True)),
            ],
        ),
    ]
